# typed: false
# frozen_string_literal: true

# This file was generated by the credential-scan release workflow. DO NOT EDIT.
require "download_strategy"

class KontextScanGitHubPrivateRepositoryReleaseDownloadStrategy < CurlDownloadStrategy
  def initialize(url, name, version, **meta)
    token = ENV["HOMEBREW_GITHUB_API_TOKEN"].to_s.strip
    odie <<~EOS if token.empty?
      HOMEBREW_GITHUB_API_TOKEN is required to install kontext-scan from the internal kontext-dev/credential-scan release repository.

      Authenticate with GitHub CLI and retry:
        HOMEBREW_GITHUB_API_TOKEN="$(gh auth token)" brew install kontext-dev/tap/kontext-scan
    EOS

    meta[:headers] ||= []
    meta[:headers] << "Authorization: Bearer #{token}"
    super
  end
end

class KontextScan < Formula
  desc "Local-first AI agent credential leak scanner for repositories and GitHub Actions"
  homepage "https://github.com/kontext-dev/credential-scan"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kontext-dev/credential-scan/releases/download/v0.1.1/kontext-scan_Darwin_amd64.tar.gz",
          using: KontextScanGitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "42d28cd04d622d51b30eb19eca0101d5cef2b3e039894646cc6cb653d9167de3"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kontext-dev/credential-scan/releases/download/v0.1.1/kontext-scan_Darwin_arm64.tar.gz",
          using: KontextScanGitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "91d09a33434cf1a2bf1b4658ad0e3789d9e616d6cc59bc746470e787232d18dc"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kontext-dev/credential-scan/releases/download/v0.1.1/kontext-scan_Linux_amd64.tar.gz",
          using: KontextScanGitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "4316f99e0c08ea18a9f0115b368b21ed22ade00fed1745e00e367704d9c04fde"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kontext-dev/credential-scan/releases/download/v0.1.1/kontext-scan_Linux_arm64.tar.gz",
          using: KontextScanGitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1f8f939373a1306089910a9d8ee51791397160c60ab8524bd48ff75ecc7c779d"
    end
  end

  def install
    bin.install "kontext-scan"
  end

  def caveats
    <<~EOS
      This formula downloads release assets from the internal kontext-dev/credential-scan repository.
      If installation fails with a GitHub authentication error, retry with:

        HOMEBREW_GITHUB_API_TOKEN="$(gh auth token)" brew install kontext-dev/tap/kontext-scan
    EOS
  end

  test do
    system bin/"kontext-scan", "--version"
  end
end
