# typed: false
# frozen_string_literal: true

# This file was generated by the Kontext release workflow. DO NOT EDIT.
require "download_strategy"
require "json"
require "utils/curl"

class KontextStagingGitHubPrivateRepositoryReleaseDownloadStrategy < CurlDownloadStrategy
  def initialize(url, name, version, **meta)
    super
    match = url.match(%r{^https://github\.com/([^/]+)/([^/]+)/releases/download/([^/]+)/(.+)$})
    raise CurlDownloadStrategyError, "unexpected release URL: #{url}" unless match
    @owner, @repo, @tag, @asset_name = match.captures
    @token = ENV["HOMEBREW_GITHUB_API_TOKEN"].to_s.strip
    odie <<~EOS if @token.empty?
      HOMEBREW_GITHUB_API_TOKEN is required to install kontext-staging: release
      assets live in the private kontext-security/kontext-cli-staging-releases repository.

      Authenticate with GitHub CLI (your account must have read access to that
      repo) and retry:
        HOMEBREW_GITHUB_API_TOKEN="$(gh auth token)" brew install kontext-security/tap/kontext-staging
    EOS
  end

  private

  def _fetch(url:, resolved_url:, timeout:)
    curl_download "https://api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}",
                  "--header", "Accept: application/octet-stream",
                  "--header", "Authorization: Bearer #{@token}",
                  to: temporary_path, timeout: timeout
  end

  def asset_id
    release = JSON.parse(Utils::Curl.curl_output(
      "--fail", "--silent", "--location",
      "--header", "Accept: application/vnd.github+json",
      "--header", "Authorization: Bearer #{@token}",
      "https://api.github.com/repos/#{@owner}/#{@repo}/releases/tags/#{@tag}"
    ).stdout)
    asset = release.fetch("assets", []).find { |a| a["name"] == @asset_name }
    odie "asset #{@asset_name} not found on #{@owner}/#{@repo} release #{@tag}" unless asset
    asset["id"]
  end
end

class KontextStaging < Formula
  desc "Identity, credentials, and governance for AI agents"
  homepage "https://kontext.security"
  version "0.0.0-staging.20260729.7"
  license "MIT"

  depends_on "llama.cpp"
  conflicts_with "kontext"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kontext-security/kontext-cli-staging-releases/releases/download/v0.0.0-staging.20260729.7/kontext_0.0.0-staging.20260729.7_darwin_amd64.tar.gz",
          using: KontextStagingGitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "ebb4cf118ffc444d78837e76494348b0e3608dda06ee7287395438933b6473ab"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kontext-security/kontext-cli-staging-releases/releases/download/v0.0.0-staging.20260729.7/kontext_0.0.0-staging.20260729.7_darwin_arm64.tar.gz",
          using: KontextStagingGitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d7259324a9f169e0ef05442f1cecef9ffe2596859f793960dba45753f834bb9c"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kontext-security/kontext-cli-staging-releases/releases/download/v0.0.0-staging.20260729.7/kontext_0.0.0-staging.20260729.7_linux_amd64.tar.gz",
          using: KontextStagingGitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d9c3e1229f1082e2c7addb717f502ed2cb5157b8569d4b3e3e0135c643624088"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kontext-security/kontext-cli-staging-releases/releases/download/v0.0.0-staging.20260729.7/kontext_0.0.0-staging.20260729.7_linux_arm64.tar.gz",
          using: KontextStagingGitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "3aba8819d8ac22776d5bb87303639370a62c8dc97e3f77b47cea73ed9c554eab"
    end
  end

  def install
    bin.install "kontext"
  end

  def caveats
    <<~EOS
      This is the STAGING build of kontext, for testing against the staging
      backend. It conflicts with the prod formula (brew uninstall kontext
      first, or vice versa).

      Point it at the staging backend before setup:
        export KONTEXT_API_URL=https://api.staging.kontext.security
        kontext setup --cloud-url https://api.staging.kontext.security --token <staging-token>

      If installation fails with a GitHub authentication error, retry with:
        HOMEBREW_GITHUB_API_TOKEN="$(gh auth token)" brew install kontext-security/tap/kontext-staging
    EOS
  end

  test do
    system bin/"kontext", "--version"
  end
end
