# typed: false
# frozen_string_literal: true

# This file was generated by the Kontext release workflow. DO NOT EDIT.
class Kontext < Formula
  desc "Identity, credentials, and governance for AI agents"
  homepage "https://kontext.security"
  version "1.0.1"
  license "MIT"

  depends_on "llama.cpp"
  conflicts_with "kontext-staging"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kontext-security/kontext-cli/releases/download/v1.0.1/kontext_1.0.1_darwin_amd64.tar.gz"
      sha256 "70b97eaee71b9b0bec2e835574d0004aaa86c2c5865437a779b3d6f636cde518"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kontext-security/kontext-cli/releases/download/v1.0.1/kontext_1.0.1_darwin_arm64.tar.gz"
      sha256 "d4d204d5d1da493aaf81a24c00a15958b0bde55ff4d5687231c8413dc10759be"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kontext-security/kontext-cli/releases/download/v1.0.1/kontext_1.0.1_linux_amd64.tar.gz"
      sha256 "ac528169d95d7f8956f7a04374e7655507eb96024e1573d56be41db5cbda6a9b"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kontext-security/kontext-cli/releases/download/v1.0.1/kontext_1.0.1_linux_arm64.tar.gz"
      sha256 "df6096674126c036c09a464257b2f67a76d72de08a79b3fd4affa44f8a6e461e"
    end
  end

  def install
    bin.install "kontext"
  end

  test do
    system bin/"kontext", "--version"
  end
end
