# typed: false
# frozen_string_literal: true

# This file was generated by the Kontext release workflow. DO NOT EDIT.
class Kontext < Formula
  desc "Identity, credentials, and governance for AI agents"
  homepage "https://kontext.security"
  version "1.1.1"
  license "MIT"

  depends_on "llama.cpp"
  conflicts_with "kontext-staging"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kontext-security/kontext-cli/releases/download/v1.1.1/kontext_1.1.1_darwin_amd64.tar.gz"
      sha256 "de14f17d11a82531c74b32a0e1a1992861e54f466600d929b4167541017d79f7"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kontext-security/kontext-cli/releases/download/v1.1.1/kontext_1.1.1_darwin_arm64.tar.gz"
      sha256 "ff5315d9a0049189861d329dd570824d47f7c4b4d6b911d35830c291b52ef847"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kontext-security/kontext-cli/releases/download/v1.1.1/kontext_1.1.1_linux_amd64.tar.gz"
      sha256 "974c045b7ba887ff222895424c44f326ab4ffb97c41f915a326ce16fcf3ec008"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kontext-security/kontext-cli/releases/download/v1.1.1/kontext_1.1.1_linux_arm64.tar.gz"
      sha256 "d6c8efce36324e42e41bd35b6156b25bd8587ab52ac073b006cd837eb92e826c"
    end
  end

  def install
    bin.install "kontext"
  end

  test do
    system bin/"kontext", "--version"
  end
end
