# typed: false
# frozen_string_literal: true

# This file was generated by Sandy's release workflow. DO NOT EDIT.
require "download_strategy"
require "json"
require "utils/curl"

class SandyGitHubPrivateRepositoryReleaseDownloadStrategy < CurlDownloadStrategy
  def initialize(url, name, version, **meta)
    super
    match = url.match(%r{^https://github\.com/([^/]+)/([^/]+)/releases/download/([^/]+)/(.+)$})
    raise CurlDownloadStrategyError, "unexpected release URL: #{url}" unless match

    @owner, @repo, @tag, @asset_name = match.captures
    @token = ENV["HOMEBREW_GITHUB_API_TOKEN"].to_s.strip
    odie <<~EOS if @token.empty?
      HOMEBREW_GITHUB_API_TOKEN is required while Sandy is distributed privately.

      Authenticate with GitHub CLI using an account with access to
      kontext-security/sandy, then retry:
        HOMEBREW_GITHUB_API_TOKEN="$(gh auth token)" brew install kontext-security/tap/sandy
    EOS
  end

  private

  def _fetch(url:, resolved_url:, timeout:)
    curl_download "https://api.github.com/repos/#{@owner}/#{@repo}/releases/assets/#{asset_id}",
                  "--header", "Accept: application/octet-stream",
                  "--header", "Authorization: Bearer #{@token}",
                  to: temporary_path, timeout: timeout
  end

  def asset_id
    release = JSON.parse(Utils::Curl.curl_output(
      "--fail", "--silent", "--location",
      "--header", "Accept: application/vnd.github+json",
      "--header", "Authorization: Bearer #{@token}",
      "https://api.github.com/repos/#{@owner}/#{@repo}/releases/tags/#{@tag}"
    ).stdout)
    asset = release.fetch("assets", []).find { |candidate| candidate["name"] == @asset_name }
    odie "asset #{@asset_name} not found on #{@owner}/#{@repo} release #{@tag}" unless asset

    asset["id"]
  end
end

class Sandy < Formula
  desc "Native macOS sandboxing for AI coding agents"
  homepage "https://kontext.security"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kontext-security/sandy/releases/download/v0.1.0/sandy_0.1.0_darwin_amd64.tar.gz",
          using: SandyGitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "9c4e6f97040bab198edb3b565a5a8844b251d727496c3377f78d733c979488f7"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kontext-security/sandy/releases/download/v0.1.0/sandy_0.1.0_darwin_arm64.tar.gz",
          using: SandyGitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c7e8c4e1cbf25d4ff48cc36612ae979008ab03227f4bbd8bc0b619c1a3fcd79b"
    end
  end

  def install
    bin.install "sandy"
  end

  def caveats
    <<~EOS
      Sandy works independently of Kontext:
        sandy run -- claude

      Sandy is currently distributed from a private GitHub repository. Keep
      HOMEBREW_GITHUB_API_TOKEN available when installing or upgrading it.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sandy --version")
  end
end
