# typed: false
# frozen_string_literal: true

# This file was generated by Sandy's release workflow. DO NOT EDIT.

class Sandy < Formula
  desc "Native macOS sandboxing for AI coding agents"
  homepage "https://kontext.security"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kontext-security/sandy/releases/download/v0.1.9/sandy_0.1.9_darwin_amd64.tar.gz"
      sha256 "881b6a492e31c98622f082dcc75a8bc2de4ff69b85fe57f6e5898752f594e90d"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kontext-security/sandy/releases/download/v0.1.9/sandy_0.1.9_darwin_arm64.tar.gz"
      sha256 "4ba365605332260be1d10ff6a35ec2167c7689da389543d68cce30a70e640ebb"
    end
  end

  def install
    bin.install "sandy"
  end

  def caveats
    <<~EOS
      Sandy works independently of Kontext:
        sandy run -- claude

      Verify that macOS sandboxing is available:
        sandy doctor
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/sandy --version")
  end
end
